name: Notify PR
description: Send a notification when a PR has been raised

runs:
  using: composite
  steps:
    - name: Notify
      if: ${{ always() }}
      uses: SimonScholz/google-chat-action@main
      with:
        webhookUrl: "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
        title: "Pull request ${{ github.event.action }}"
        subtitle: "${{ github.event.pull_request.title }}"
