name: Create Tag
description: Create a tag
inputs:
  gpg-key:
    description: The GPG key
    required: true
    type: string
  gpg-password:
    description: The password for the GPG key
    required: true
    type: string
  tag:
    description: Tag value
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.gpg-key }}
        passphrase: ${{ inputs.gpg-password }}
        git_user_signingkey: true
        git_tag_gpgsign: true
    - name: Create tag
      shell: pwsh
      run: |
        git tag -s "${{ inputs.tag }}" -m "${{ inputs.tag }}"
    - name: Push tag
      shell: pwsh
      run: |
        git push origin tag "${{ inputs.tag }}"
