name: Tag
description: Create a tag
author: Cupel

inputs:
  ssh-private-key:
    description: The private SSH key
    required: true
  ssh-public-key:
    description: The private SSH key
    required: true
  tag:
    description: Tag value
    required: true

runs:
  using: composite
  steps:
    - name: Add SSH Key
      shell: bash
      run: |
        eval $(ssh-agent -s)
        echo "${{ inputs.ssh-private-key }}" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh-public-key }}" > ~/.ssh/signing.pub
        chmod 600 ~/.ssh/signing.pub
        echo "${{ inputs.ssh-private-key }}" | tr -d '\r' > ~/.ssh/signing
        chmod 600 ~/.ssh/signing
        ssh-add -l
    - name: Configure Git for SSH signing
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global user.signingkey /home/runner/.ssh/signing.pub
        git config --global gpg.format ssh
        git config --global gpg.ssh.program "ssh-keygen"
        git config --global commit.gpgsign true
        git config --global tag.gpgsign true

        mkdir -p ~/.ssh
        echo "Host github-signing-key" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/signing" >> ~/.ssh/config
    - name: Create tag
      shell: bash
      run: |
        git tag -s '${{ inputs.tag }}' -m '${{ inputs.tag }}'
    - name: Push tag
      shell: bash
      run: |
        git push origin tag '${{ inputs.tag }}'

