name: Download Artifact
description: Download and extract a tar artifact that was previously uploaded in the workflow by the upload-artifact action
author: Cupel

inputs:
  name:
    description: Artifact name
    required: true
  path:
    description: Destination path
    required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: '${{ inputs.name }}'
        path: '${{ inputs.path }}'

    - run: |
        tar -xvf artifact.tar
      working-directory: '${{ inputs.path }}'
      shell: bash

    - run: |
        rm artifact.tar
      working-directory: '${{ inputs.path }}'
      shell: bash
