name: Update PR Description
description: Update PR Description
author: Cupel

inputs:
  environment:
    description: The environment name
    required: true
outputs:
  description:
    description: The pull request description with replaced values
    value: ${{ steps.replace-values.outputs.description }}

runs:
  using: composite
  steps:
    - name: Get issue details
      id: get-issue-details
      shell: bash
      run: |
        shopt -s nocasematch
        branch="${{ github.head_ref }}"
        if [[ "$branch" =~ GH-([0-9]+) ]]; then
          number="${BASH_REMATCH[1]}"
          echo "Issue Number: $number"
          echo "number=$number" >> "$GITHUB_OUTPUT"
        
          title=$(gh issue view "$number" --repo "${{ github.repository }}" --json title --jq '.title')
          echo "Issue Title: $title"
          echo "title=$title" >> "$GITHUB_OUTPUT"
        else
          echo "number=Unknown" >> "$GITHUB_OUTPUT"
          echo "title=Unknown" >> "$GITHUB_OUTPUT"
        fi
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Replace values
      id: replace-values
      shell: bash
      run: |
        repository="${{ github.repository }}"
        branch="${{ github.head_ref }}"
        environment="${{ inputs.environment }}"
        
        issueNumber="${{ steps.get-issue-details.outputs.number }}"
        issueTitle="${{ steps.get-issue-details.outputs.title }}"
        
        prNumber="${{ github.event.pull_request.number }}"
        prTitle="${{ github.event.pull_request.title }}"
        prDescription="${{ github.event.pull_request.body }}"

        description="${prDescription//'{{REPOSITORY}}'/$repository}"
        description="${description//'{{BRANCH_NAME}}'/$branch}"
        description="${description//'{{ENVIRONMENT}}'/$environment}"
        description="${description//'{{ISSUE_NUMBER}}'/$issueNumber}"
        description="${description//'{{ISSUE_TITLE}}'/$issueTitle}"
        description="${description//'{{PULL_REQUEST_NUMBER}}'/$prNumber}"
        description="${description//'{{PULL_REQUEST_TITLE}}'/$prTitle}"
        {
          echo "description<<EOF"
          echo "$description"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
    - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # use https://github.com/actions/github-script/releases/tag/v9.0.0
      name: Update Pull Request Description
      env:
        PR_BODY: '${{ steps.replace-values.outputs.description }}'
        INPUT_PR_NUMBER: ${{ github.event.pull_request.number }}
        CONTEXT_PR_NUMBER: ${{ github.event.number }}
      with:
        script: |
          const body = process.env.PR_BODY;
          const prNumber = process.env.INPUT_PR_NUMBER || process.env.CONTEXT_PR_NUMBER;                    
          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
            body: body
          });
