name: Update PR Description
description: Update PR Description
author: Cupel

inputs:
  environment:
    description: The environment name
    required: true
outputs:
  description:
    description: The pull request description with replaced values
    value: ${{ steps.replace-values.outputs.description }}

runs:
  using: composite
  steps:
    - name: Get issue details
      id: get-issue-details
      shell: bash
      run: |
        $branch="${{ github.head_ref }}"
        if ($branch -match "GH-(\d+)-") {
          $number = $matches[1]
          Write-Output "Issue Number: $number"
          "number=$number" >> $env:GITHUB_OUTPUT
        
          $title = $(gh issue view $number --repo '${{ github.repository }}' --jq '.title' --json title)
          Write-Output "Issue Title: $title"
          "title=$title" >> $env:GITHUB_OUTPUT
        } else {
          Write-Output "::error No issue number found in branch name"
          exit 1
        }
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Replace values
      id: replace-values
      shell: bash
      run: |
        repository="${{ github.repository }}"
        branch="${{ github.head_ref }}"
        environment="${{ inputs.environment }}"
        
        issueNumber="${{ steps.get-issue-details.outputs.number }}"
        issueTitle="${{ steps.get-issue-details.outputs.title }}"
        
        prNumber="${{ github.event.pull_request.number }}"
        prTitle="${{ github.event.pull_request.title }}"
        prDescription="${{ github.event.pull_request.body }}"

        description="${prDescription//'{{REPOSITORY}}'/$repository}"
        description="${description//'{{BRANCH_NAME}}'/$branch}"
        description="${description//'{{ENVIRONMENT}}'/$environment}"
        description="${description//'{{ISSUE_NUMBER}}'/$issueNumber}"
        description="${description//'{{ISSUE_TITLE}}'/$issueTitle}"
        description="${description//'{{PULL_REQUEST_NUMBER}}'/$prNumber}"
        description="${description//'{{PULL_REQUEST_TITLE}}'/$prTitle}"
        {
          echo "description<<EOF"
          echo "$description"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Update Pull Request Description
      uses: vblagoje/update-pr@v1
      with:
        pr-number: ${{ github.event.pull_request.number }}
        pr-body: '${{ steps.replace-values.outputs.description }}'
