name: OpenTofu Apply
description: Apply changes to infrastructure
author: Cupel
branding: 
  icon: box
  color: orange

inputs:
  apply-args:
    description: Additional arguments for init command.
    required: false
    type: string
  version:
    description: The version of OpenTofu to install.
    required: true
    default: 1.8.1
    type: string

runs:
  using: composite
  steps:
    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: "${{ inputs.version }}"
    - name: Apply
      shell: pwsh
      run: |
        ls -al
        tofu apply -no-color -auto-approve -lock=true ${{ inputs.apply-args }} "plan.tfplan"
      env:
        TF_IN_AUTOMATION: 1
        TF_INPUT: 0
