name: Delete Artifact
description: Delete an uploaded artifact
author: Cupel

inputs:
  name:
    description: Artifact name
    required: true

runs:
  using: composite
  steps:
    - name: 'Delete ${{ inputs.name }}'
      uses: geekyeggo/delete-artifact@v5
      with:
        name: '${{ inputs.name }}'
