name: Breakdown
description: Breakdown infrastructure costs with Infracost
inputs:
  api-key:
    description: Infracost API Key
    required: true
    type: string
  currency:
    description: The currency to show estimates in
    default: AUD
    required: false
    type: string
  output-path:
    description: The file path for the JSON file
    default: ./infracost.json
    required: false
    type: string
  template:
    description: The infracost template
    required: false
    type: string
    default: ""
  workspace-prefix:
    description: The prefix for the workspace name
    required: false
    type: string
    default: ""
  version:
    description: The version of Infracost to install
    default: 0.10.x
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Setup Infracost
      uses: infracost/actions/setup@v3
      with:
        api-key: ${{ inputs.api-key }}
        currency: ${{ inputs.currency }}
        version: ${{ inputs.version }}
    - name: Generate config
      shell: pwsh
      run: |
        $template = ""
        
        if ('${{ inputs.template }}'.Trim() -ne '') {
        $template = @"
        ${{ inputs.template }}
        "@
        } else {
        $template = @"
        version: 0.1
        projects:
        {{- range `$project := matchPaths "infrastructure/variables/:env.tfvars" }}
            - path: "./infrastructure"
              name: "{{ `$project.env }}"
              terraform_workspace: "${{ inputs.workspace-prefix }}{{ `$project.env }}"
              terraform_var_files:
                - "{{ relPath "./infrastructure" `$project._path }}"
              dependency_paths:
                - "**"
                - "{{ relPath "./infrastructure" `$project._path }}"
        {{- end }}
        "@
        }

        infracost generate config --out-file infracost.yml --template $template 
    - name: Breakdown
      shell: pwsh
      run: |
        infracost breakdown --config-file infracost.yml --out-file ${{ inputs.output-path }} --format json --fields all
