name: OpenTofu Plan
description: Generate a plan
author: Cupel

inputs:
  init-args:
    description: Additional arguments for init command.
    required: false
  plan-args:
    description: Additional arguments for plan command.
    required: false
  use-primary-backend:
    description: A flag to indicate if the primary backend should be used.
    default: 'true'
    required: true
  version:
    description: The version of OpenTofu to install.
    default: 1.8.1
    required: true
  working-directory:
    description: Directory that contains the OpenTofu code.
    default: ./infrastructure
    required: true
  workspace:
    description: The workspace name. If the workspace doesn't exist it will be created.
    required: true

outputs:
  CHANGES:
    description: 'Indicates if the plan detected changes (true) or not (false). Value is empty string if plan failed.'
    value: ${{ steps.plan.outputs.CHANGES }}

runs:
  using: composite
  steps:
    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: '${{ inputs.version }}'
    - name: Init
      shell: bash
      working-directory: '${{ inputs.working-directory }}'
      run: |
        exec tofu init -no-color -lockfile=readonly -lock=false -var 'use_primary_backend=${{ inputs.use-primary-backend }}' ${{ inputs.init-args }}
      env:
        TF_IN_AUTOMATION: 1
        TF_INPUT: 0
    - name: Select workspace
      shell: bash
      working-directory: '${{ inputs.working-directory }}'
      run: |
        exec tofu workspace select -or-create=true '${{ inputs.workspace }}'
      env:
        TF_IN_AUTOMATION: 1
        TF_INPUT: 0
    - name: Plan
      id: plan
      shell: bash
      working-directory: '${{ inputs.working-directory }}'
      run: |
        exec tofu plan -no-color -out='plan.tfplan' -detailed-exitcode -var 'use_primary_backend=${{ inputs.use-primary-backend }}' ${{ inputs.plan-args }}
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
         echo "CHANGES=false" >> "$GITHUB_OUTPUT"
        elif [ $exit_code -eq 2 ]; then
         echo "CHANGES=true" >> "$GITHUB_OUTPUT"
        else
         exit $exit_code
        fi
      env:
        TF_IN_AUTOMATION: 1
        TF_INPUT: 0
