name: Release
description: Create a release from a GitHub tag
inputs:
  tag:
    description: Tag value
    required: true
    type: string
  token:
    description: GitHub Token to use. This can be a PAT.
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Generate changelog
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        includeInvalidCommits: true
        token: "${{ inputs.token }}"
        tag: "${{ inputs.tag }}"
        writeToFile: false
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        body: "${{ steps.changelog.outputs.changes }}"
        tag_name: "${{ inputs.tag }}"
        make_latest: true
        token: "${{ inputs.token }}"
