name: Comment
description: Add a comment to the PR in GitHub
inputs:
  api-key:
    description: Infracost API Key
    required: true
    type: string
  behaviour:
    description: The behaviour for the comment
    default: update
    required: false
    type: choice
    options:
      - delete-and-new
      - hide-and-new
      - new
      - update
  comment-identifier:
    description: A unique identifier to for the comment added by this implementation
    default: infracost
    required: false
    type: string
  currency:
    description: The currency to show estimates in
    default: AUD
    required: false
    type: string
  path:
    description: The path to the JSON report file
    required: true
    type: string
  pull-request-number:
    description: The PR number
    required: true
    type: number
  repository:
    description: The repository name
    required: true
    type: string
  token:
    description: The GitHub token
    required: true
    type: string
  version:
    description: The version of Infracost to install
    default: 0.10.x
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Setup Infracost
      uses: infracost/actions/setup@v3
      with:
        api-key: ${{ inputs.api-key }}
        currency: ${{ inputs.currency }}
        version: ${{ inputs.version }}
    - name: Comment
      shell: pwsh
      run: |
        infracost comment github `
          --path=${{ inputs.path }} `
          --repo=${{ inputs.repository }} `
          --pull-request=${{ inputs.pull-request-number }} `
          --github-token=${{ inputs.token }} `
          --behavior=${{ inputs.behaviour }} `
          --show-all-projects `
          --tag=infracost-${{ inputs.comment-identifier }}
