name: OpenTofu Cost Comment
description: Add a comment to the PR in GitHub
author: Cupel

inputs:
  api-key:
    description: Infracost API Key
    required: true
  behaviour:
    description: The behaviour for the comment (delete-and-new,hide-and-new, new, update)
    default: update
    required: false
  comment-identifier:
    description: A unique identifier to for the comment added by this implementation
    default: comment
    required: false
  currency:
    description: The currency to show estimates in
    default: AUD
    required: false
  path:
    description: The path to the JSON report file
    required: true
  pull-request-number:
    description: The PR number
    required: true
  repository:
    description: The repository name
    required: true
  token:
    description: The GitHub token
    required: true
  version:
    description: The version of Infracost to install
    default: 0.10.x
    required: false
  working-directory:
    description: Directory that contains the OpenTofu code.
    default: ./infrastructure
    required: true

runs:
  using: composite
  steps:
    - name: Setup Infracost
      uses: infracost/actions/setup@v3
      with:
        api-key: ${{ inputs.api-key }}
        currency: ${{ inputs.currency }}
        version: ${{ inputs.version }}
    - name: Comment
      shell: bash
      working-directory: '${{ inputs.working-directory }}'
      run: |
        exec infracost comment github \
          --path=${{ inputs.path }} \
          --repo=${{ inputs.repository }} \
          --pull-request=${{ inputs.pull-request-number }} \
          --github-token=${{ inputs.token }} \
          --behavior=${{ inputs.behaviour }} \
          --show-all-projects \
          --tag=infracost-${{ inputs.comment-identifier }}
