name: OpenTofu Get
description: Install OpenTofu modules
author: Cupel

inputs:
  version:
    description: The version of OpenTofu to install.
    default: 1.8.1
    required: true
  working-directory:
    description: Directory that contains the OpenTofu code.
    default: ./infrastructure
    required: true

runs:
  using: composite
  steps:
    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: '${{ inputs.version }}'
    - name: Get
      shell: bash
      working-directory: '${{ inputs.working-directory }}'
      run: |
        exec tofu get -no-color
      env:
        TF_IN_AUTOMATION: 1
        TF_INPUT: 0
