name: OpenTofu Static Analysis
description: OpenTofu Static Analysis
author: Cupel

inputs:
  working-directory:
    description: Directory that contains the OpenTofu code
    default: ./infrastructure
    required: true

runs:
  using: composite
  steps:
    - name: Run
      uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
      with:
        github_token: '${{ github.token }}'
        working_directory: '${{ inputs.working-directory }}'
