name: Terrakube CLI Apply
description: Apply changes to infrastructure using Terrakube as the cloud backend
author: Cupel

inputs:
  init-args:
    description: Additional arguments for init command.
    required: false
  apply-args:
    description: Additional arguments for apply command.
    required: false
  version:
    description: The version of OpenTofu to install.
    default: 1.11.6
    required: true
  working-directory:
    description: Directory that contains the OpenTofu code.
    default: ./infrastructure
    required: true
  terrakube-hostname:
    description: The hostname of your Terrakube instance (e.g., terrakube.example.com).
    required: true
    default: https://terrakube-api.cicd.cupel.co
  terrakube-token:
    description: The API token for authenticating with Terrakube.
    required: true

runs:
  using: composite
  steps:
    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: '${{ inputs.version }}'
        cli_config_credentials_hostname: '${{ inputs.terrakube-hostname }}'
        cli_config_credentials_token: '${{ inputs.terrakube-token }}'

    - name: Init
      shell: bash
      working-directory: '${{ inputs.working-directory }}'
      run: tofu init -no-color ${{ inputs.init-args }}
      env:
        TF_IN_AUTOMATION: 1
        TF_INPUT: 0
        TF_VAR_terrakube_hostname: '${{ inputs.terrakube-hostname }}'

    - name: Apply
      shell: bash
      working-directory: '${{ inputs.working-directory }}'
      run: tofu apply -no-color ${{ inputs.apply-args }}
      env:
        TF_IN_AUTOMATION: 1
        TF_INPUT: 0
        TF_VAR_terrakube_hostname: '${{ inputs.terrakube-hostname }}'
