name: Generate Semantic Version
description: Generate Semantic Version
    
outputs:
  major:
    description: 'The Major value'
    value: ${{ steps.generate.outputs.major }}
  minor:
    description: 'The Minor value'
    value: ${{ steps.generate.outputs.minor }}
  patch:
    description: 'The Patch value'
    value: ${{ steps.generate.outputs.patch }}
  preReleaseTag:
    description: 'The PreReleaseTag value'
    value: ${{ steps.generate.outputs.preReleaseTag }}
  preReleaseTagWithDash:
    description: 'The PreReleaseTagWithDash value'
    value: ${{ steps.generate.outputs.preReleaseTagWithDash }}
  preReleaseLabel:
    description: 'The PreReleaseLabel value'
    value: ${{ steps.generate.outputs.preReleaseLabel }}
  preReleaseNumber:
    description: 'The PreReleaseNumber value'
    value: ${{ steps.generate.outputs.preReleaseNumber }}
  weightedPreReleaseNumber:
    description: 'The WeightedPreReleaseNumber value'
    value: ${{ steps.generate.outputs.weightedPreReleaseNumber }}
  buildMetaData:
    description: 'The BuildMetaData value'
    value: ${{ steps.generate.outputs.buildMetaData }}
  fullBuildMetaData:
    description: 'The FullBuildMetaData value'
    value: ${{ steps.generate.outputs.fullBuildMetaData }}
  majorMinorPatch:
    description: 'The MajorMinorPatch value'
    value: ${{ steps.generate.outputs.majorMinorPatch }}
  semVer:
    description: 'The SemVer value'
    value: ${{ steps.generate.outputs.semVer }}
  assemblySemVer:
    description: 'The AssemblySemVer value'
    value: ${{ steps.generate.outputs.assemblySemVer }}
  assemblySemFileVer:
    description: 'The AssemblySemFileVer value'
    value: ${{ steps.generate.outputs.assemblySemFileVer }}
  fullSemVer:
    description: 'The FullSemVer value'
    value: ${{ steps.generate.outputs.fullSemVer }}
  informationalVersion:
    description: 'The InformationalVersion value'
    value: ${{ steps.generate.outputs.informationalVersion }}
  branchName:
    description: 'The BranchName value'
    value: ${{ steps.generate.outputs.branchName }}
  escapedBranchName:
    description: 'The EscapedBranchName value'
    value: ${{ steps.generate.outputs.escapedBranchName }}
  sha:
    description: 'The Sha value'
    value: ${{ steps.generate.outputs.sha }}
  shortSha:
    description: 'The ShortSha value'
    value: ${{ steps.generate.outputs.shortSha }}
  versionSourceSha:
    description: 'The VersionSourceSha value'
    value: ${{ steps.generate.outputs.versionSourceSha }}
  commitsSinceVersionSource:
    description: 'The CommitsSinceVersionSource value'
    value: ${{ steps.generate.outputs.commitsSinceVersionSource }}
  uncommittedChanges:
    description: 'The UncommittedChanges value'
    value: ${{ steps.generate.outputs.uncommittedChanges }}
  commitDate:
    description: 'The CommitDate value'
    value: ${{ steps.generate.outputs.commitDate }}

runs:
  using: composite
  steps:
    - name: Install
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'
    - name: Generate
      id: generate
      uses: gittools/actions/gitversion/execute@v1.1.1
      with:
        targetPath: ./
        disableCache: true
        useConfigFile: true
        configFilePath: GitVersion.yml
      env:
        BUILD_NUMBER: ${{ github.run_number }}
